In [1]:
import cv2
import pymynt
import numpy as np

watching_point = None

pymynt.init_camera('raw')

In [2]:
def depth2img(mat):
    out = mat/np.max(mat)*255
    out = out.astype('uint8')
    out = cv2.cvtColor(out, cv2.COLOR_GRAY2RGB)
    return out

In [3]:
mat = pymynt.get_depth_image()
mat

array([[256,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint16)

In [24]:
edit = np.where((mat>400) & (mat<500),1,0)
boxline = np.where(np.sum(edit,0)>25,1,0)

box = []
bias = 0
boxlinecut = boxline.copy()
while boxlinecut.shape[0]>0:
    _ = np.where(boxlinecut==1)[0]
    if _.shape[0]>0:
        left = _[0] + bias
        bias += _[0]
    else:
        break
    boxlinecut = boxline.copy()[bias:]
    _ = np.where(boxlinecut==0)[0]
    if _.shape[0]>0:
        right = _[0] -1 + bias
        bias += _[0]
    else:
        right = mat.shape[0]
        bias = mat.shape[0]
    box += [(left,right)]
    boxlinecut = boxline.copy()[bias:]
        
print(box)

cv2.imshow('depth',depth2img(edit))
cv2.waitKey(1000)
cv2.destroyAllWindows()

[(612, 897), (899, 899)]


In [ ]:
while left_index<mat.shape[1]:
    

In [29]:
_ = np.where(boxline==1)[0]
_.shape[0]>0

312

In [47]:
_1=490
np.sum(edit,0)[_1:_1+20]

array([35, 30, 30, 27, 25, 29, 30, 33, 26, 24, 29, 21, 19, 13, 11, 11, 15,
       14, 16, 15])

In [15]:
boxline[::50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0])

In [16]:
cv2.imshow('depth',depth2img(edit))
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [25]:
_boxline = boxline

In [20]:
boxline = _boxline

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1])